---
 - name: checking conf file exists exists
   stat:
     path: /usr/share/doc/sensu-go-agent-5.3.0/agent.yml.example
   register: p
      
 - name: repo
   shell: "curl -s https://packagecloud.io/install/repositories/sensu/stable/script.rpm.sh | sudo bash"
   when: p.stat.exists == False
      
 - name: package
   package:
     name: sensu-go-agent
     state: present
      
 - name: template
   template:
     src: agent.yml.j2
     dest: /etc/sensu/agent.yml
...
