---
 - name: "add yum repo"
   yum_repository:
     name: MariaDB
     description: Official MariaDB repository
     baseurl: http://yum.mariadb.org/10.1/centos7-amd64
     gpgkey: https://yum.mariadb.org/RPM-GPG-KEY-MariaDB
     gpgcheck: true
 - name: selinux
   command: setenforce 0

 - name: "Install package"
   package:
     name: "{{ item }}"
     state: installed
   loop: "{{ mariadb_packages }}"
...
