---
 - name: Check if root password is set
   shell: >
    mysqladmin -u root status
   changed_when: false
   failed_when: false
   register: root_pwd_check
   tags: mariadb

 - name: change root password
   shell: "mysqladmin -u root --password='' password 'password'"    
   when: root_pwd_check.rc == 0
   tags: mariadb
   notify: restartmariadb

# - name: Update root password
#   mysql_user: name=root host={{item}} password={{root_password}}
#   with_items:
#     - "{{ ansible_hostname }}"
#     - 127.0.0.1
#     - ::1
#     - localhost
 
# - name: Copy the root credentials as .my.cnf file
#   template: src=root.cnf.j2 dest=~/.my.cnf mode=0600

# - name: Remove anonymous users
#   mysql_user: name='' host_all=yes state=absent
#   when: root_pwd_check.rc == 0

# - name: Remove test database
#   mysql_db: name=test state=absent
#
# - name: delete anonymous MySQL server user for {{ ansible_hostname }}
#   action: mysql_user user="" host="{{ ansible_hostname }}" state="absent"
#
#
#- name: Sets the root password 
#   mysql_user: user=root password="{{ mysql_root_password }}" host=localhost

# - name: Set the root password 
#   mysql_user: login_user=root login_password="{{ root_password }}" user=root password="{{ root_password }}"
# - name: Deletes anonymous MySQL server user for ansible_fqdn
#   mysql_user: login_user=root login_password="{{ root_password }}" user=root host="{{ ansible_fqdn }}" state="absent"

# - name: Deletes anonymous MySQL server user for localhost
#   mysql_user: user="" state="absent"

