---
 - name: enable and restar mariadb
   service:
     name: mariadb
     enabled: yes
     state: restarted
 - name: firewall disable
   service:
     name: firewalld
     state: stopped
     enabled: no
...
